/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author madmm
 */
public class Login extends javax.swing.JFrame {

    //for login
    static String user;
    static String loginid;
    static String pass;
    static boolean foundid = false;
    //for getuser
    static long count;
    static String date;
    static String u_pass;
    static String u_type;

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_ID = new javax.swing.JTextField();
        TextField_pass = new javax.swing.JTextField();
        Label_ID = new javax.swing.JLabel();
        Label_pass = new javax.swing.JLabel();
        Button_log = new javax.swing.JButton();
        Label_logo = new javax.swing.JLabel();
        Label_reg = new javax.swing.JLabel();
        Button_reg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        TextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_IDActionPerformed(evt);
            }
        });

        TextField_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_passActionPerformed(evt);
            }
        });

        Label_ID.setText("ID / phone number");

        Label_pass.setText("password");

        Button_log.setText("Login");
        Button_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_logActionPerformed(evt);
            }
        });

        Label_logo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_logo.setText("Inthanin");

        Label_reg.setText("New here?");

        Button_reg.setText("sign up");
        Button_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(Label_logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_reg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label_pass)
                                .addComponent(Label_ID)
                                .addComponent(TextField_ID)
                                .addComponent(TextField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(Label_logo)
                .addGap(18, 18, 18)
                .addComponent(Label_ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_pass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_reg)
                    .addComponent(Button_reg))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_IDActionPerformed
        user = TextField_ID.getText();
        TextField_pass.requestFocus();
    }//GEN-LAST:event_TextField_IDActionPerformed

    private void TextField_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_passActionPerformed
        pass = TextField_pass.getText();
        Button_log.requestFocus();
    }//GEN-LAST:event_TextField_passActionPerformed

    private static void getUsername() {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Login");

            DBCursor cursor = table.find();
            count = cursor.count();
        } catch (Exception e) {
        }
        if (count > 99 || count == 99) {
            loginid = "L" + (count + 1);
        } else if (count > 9 || count == 9) {
            loginid = "L0" + (count + 1);
        } else {
            loginid = "L00" + (count + 1);
        }
        System.out.println(loginid);
    }

    private void getTrnLogin() {
        
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Login");
            BasicDBObject document = new BasicDBObject();

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM dd, yyyy HH:mm:ss a");
            LocalDateTime now = LocalDateTime.now();
            date = dtf.format(now);
            getUsername();

            document.put("TRN_Login_Id", loginid);
            document.put("MS_Employee_Id", user);
            document.put("TRN_Login_ClockIn", date);
            document.put("TRN_Login_ClockOut", "");
            document.put("TRN_Login_Type", u_type);

            table.insert(document);
            System.out.println("ok");
            Menu newmenu = new Menu();
            newmenu.getid(user, loginid, "login");
            newmenu.setVisible(true);
            foundid = false;
            this.setVisible(false);

        } catch (Exception e) {
        }

    }
    private void Button_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_logActionPerformed
        user = TextField_ID.getText();
        pass = TextField_pass.getText();
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);

            DB db = mongo.getDB("inthanin");

            DBCollection table = db.getCollection("MS_Employee");
            BasicDBObject searchQuery = new BasicDBObject();

            searchQuery.put("MS_Employee_Id", user);
            DBCursor cursor = table.find(searchQuery);
            while (cursor.hasNext()) {
                DBObject obj = cursor.next();
                u_pass = (String) obj.get("MS_Employee_Pass");
                u_type = (String) obj.get("MS_Employee_Type");
                if (pass.equals(u_pass)) {
                    System.out.println("Successfully");
                    getTrnLogin();
                    foundid = true;
                    TextField_ID.setText("");
                    TextField_pass.setText("");
                } else {
                    System.out.println("Password Incorrect");
                    JOptionPane.showMessageDialog(this, "Password Incorrect");
                    TextField_pass.setText("");
                }
                break;
            }
            if (foundid == false) {
                System.out.println("Id incorrect");
                JOptionPane.showMessageDialog(this, "ID incorrect");
                TextField_ID.setText("");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_Button_logActionPerformed

    private void Button_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_regActionPerformed
        Sign newsu = new Sign();
        newsu.setVisible(true);
    }//GEN-LAST:event_Button_regActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_log;
    private javax.swing.JButton Button_reg;
    private javax.swing.JLabel Label_ID;
    private javax.swing.JLabel Label_logo;
    private javax.swing.JLabel Label_pass;
    private javax.swing.JLabel Label_reg;
    private javax.swing.JTextField TextField_ID;
    private javax.swing.JTextField TextField_pass;
    // End of variables declaration//GEN-END:variables
}
