/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author madmm
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getTime();

    }
    static String empid;
    static String logid;
    static String log_type;
    static String name;
    static String type;
    static String date;
    static boolean FoundId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_emp = new javax.swing.JLabel();
        TextField_date = new javax.swing.JTextField();
        Label_date = new javax.swing.JLabel();
        Label_time = new javax.swing.JLabel();
        TextField_time1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Button_logout = new javax.swing.JButton();
        Label_menu = new javax.swing.JLabel();
        Button_signup = new javax.swing.JButton();
        Button_order = new javax.swing.JButton();
        Button_rep = new javax.swing.JButton();
        Button_mem = new javax.swing.JButton();
        Button_product = new javax.swing.JButton();
        TextField_emp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_emp.setText("Employee:");

        TextField_date.setEditable(false);
        TextField_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_dateActionPerformed(evt);
            }
        });

        Label_date.setText("Date:");

        Label_time.setText("Time:");

        TextField_time1.setEditable(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        Button_logout.setText("Logout");
        Button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_logoutActionPerformed(evt);
            }
        });

        Label_menu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_menu.setText("Menu");

        Button_signup.setText("Signup");
        Button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_signupActionPerformed(evt);
            }
        });

        Button_order.setText("Ordering");
        Button_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_orderActionPerformed(evt);
            }
        });

        Button_rep.setText("Report");
        Button_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_repActionPerformed(evt);
            }
        });

        Button_mem.setText("Member");
        Button_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_memActionPerformed(evt);
            }
        });

        Button_product.setText("Product");
        Button_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Label_menu)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Button_mem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(Button_product, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_order, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(Button_rep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_order, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_rep, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_mem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_product, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TextField_emp.setEditable(false);
        TextField_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_empActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Label_time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_time1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_emp)
                    .addComponent(TextField_time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_time)
                    .addComponent(Label_date)
                    .addComponent(TextField_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_dateActionPerformed

    }//GEN-LAST:event_TextField_dateActionPerformed

    private void Button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_logoutActionPerformed
        getTrnLogout();
    }//GEN-LAST:event_Button_logoutActionPerformed

    private void Button_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_orderActionPerformed
        Order newo = new Order();
        newo.setVisible(true);
        newo.getid(empid, logid);
    }//GEN-LAST:event_Button_orderActionPerformed

    private void Button_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_repActionPerformed
        Report newrp = new Report();
        newrp.setVisible(true);
        newrp.getid(empid, logid);
    }//GEN-LAST:event_Button_repActionPerformed

    private void Button_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_productActionPerformed
        Product_Manage newpm = new Product_Manage();
        newpm.setVisible(true);
        newpm.getid(empid, logid);
    }//GEN-LAST:event_Button_productActionPerformed

    private void Button_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_memActionPerformed
        Member newmem = new Member();
        newmem.setVisible(true);
    }//GEN-LAST:event_Button_memActionPerformed

    private void Button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_signupActionPerformed
        Sign newsu = new Sign();
        newsu.setVisible(true);
    }//GEN-LAST:event_Button_signupActionPerformed

    private void TextField_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_empActionPerformed

    public void getid(String id, String loginid, String type) {
        empid = id;
        logid = loginid;
        log_type = type;
        System.out.println(empid + " " + logid);
        getemp();

    }

    public void getTime() {
        Date d = new Date();
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("HH:mm:ss");
                SimpleDateFormat t = new SimpleDateFormat("YYYY-MM-dd");
                TextField_date.setText(t.format(d));
                TextField_time1.setText(s.format(d));
            }
        }).start();

    }

    public void getemp() {

        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Employee");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();
            searchQuery.put("MS_Employee_Id", empid);
            DBCursor cursor = table.find(searchQuery);
            if (cursor.hasNext() == true) {
                for (DBObject a : cursor) {
                    System.out.println(cursor.next());
                    String fname = (String) a.get("MS_Employee_Fname");
                    String lname = (String) a.get("MS_Employee_Lname");
                    type = (String) a.get("MS_Employee_Type");
                    name = lname + " " + fname + " (" + type + ")";
                    TextField_emp.setText(name);
                }
            } else {
                System.out.println("Please select id");
            }

        } catch (Exception e) {
        }
    }

    private void getTrnLogout() {
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM dd, yyyy HH:mm:ss a");
            LocalDateTime now = LocalDateTime.now();
            date = dtf.format(now);

            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Login");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();
            searchQuery.put("TRN_Login_Id", logid);
            System.out.println(logid);
            DBCursor cursor = table.find(searchQuery);
            while (cursor.hasNext()) {
                System.out.println(cursor.next());
                System.out.println("log out  ...");

                System.out.println(date);
                String logout = "logout";
                BasicDBObject newDocument = new BasicDBObject();
                DBObject query = new BasicDBObject().append("TRN_Login_ClockOut", "");
                newDocument.append("$set", new BasicDBObject().append("TRN_Login_ClockOut", date));
                table.update(query, newDocument);

                FoundId = false;
                System.out.println("ok");
                break;
            }

            Login newlogin = new Login();
            this.setVisible(false);
            newlogin.setVisible(true);
        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_logout;
    private javax.swing.JButton Button_mem;
    private javax.swing.JButton Button_order;
    private javax.swing.JButton Button_product;
    private javax.swing.JButton Button_rep;
    private javax.swing.JButton Button_signup;
    private javax.swing.JLabel Label_date;
    private javax.swing.JLabel Label_emp;
    private javax.swing.JLabel Label_menu;
    private javax.swing.JLabel Label_time;
    private javax.swing.JTextField TextField_date;
    private javax.swing.JTextField TextField_emp;
    private javax.swing.JTextField TextField_time1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
