/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author madmm
 */
public final class Order extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    static String menuid;
    static String username;
    static String useror;
    static String pid;
    static String settp = "";
    static String my_price = "";
    static List<DBObject> list = new ArrayList<>();
    static ArrayList<ord> arr = new ArrayList<>();
    static int countno = 1;
    static long count = 0;
    static double price_total = 0;
    static double ur_price = 0;
    static double last_price = 0;
    static String cusphone;
    static String date;
    //for header
    static String name;
    static String empid;
    static String logid;
    static String type;
    //for customer
    static String cname;
    static String cid;
    //for invoice
    boolean check1 = false;
    boolean check2 = false;
    Font TopFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    Font Topic = new Font(Font.FontFamily.COURIER, 24, Font.BOLD);
    Font Bold = new Font(Font.FontFamily.COURIER, 18, Font.BOLD);
    Font minimal = new Font(Font.FontFamily.COURIER, 8, Font.BOLD);
    Font normal = new Font(Font.FontFamily.COURIER, 15, Font.NORMAL);

    String[] coln = {"num", "id", "name", "price", "type"};
    DefaultTableModel model = new DefaultTableModel(coln, 0) {
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    public Order() {
        initComponents();
        setPane(Panel_cal);
        setTable();
        getTime();
    }

    public void setPane(JPanel pane) {
        layeredpane.removeAll();
        layeredpane.add(pane);
        layeredpane.repaint();
        layeredpane.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_time = new javax.swing.JLabel();
        Label_date = new javax.swing.JLabel();
        Label_emp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Button_Bev = new javax.swing.JButton();
        Button_Bake = new javax.swing.JButton();
        Button_Etc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_cancelorder = new javax.swing.JButton();
        layeredpane = new javax.swing.JLayeredPane();
        Panel_cal = new javax.swing.JPanel();
        Button_7 = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_1 = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        Button_0 = new javax.swing.JButton();
        Button_00 = new javax.swing.JButton();
        Button_dot = new javax.swing.JButton();
        Button_equal = new javax.swing.JButton();
        Button_backspace = new javax.swing.JButton();
        Button_clear = new javax.swing.JButton();
        Button_payment = new javax.swing.JButton();
        Label_price = new javax.swing.JLabel();
        Label_cash = new javax.swing.JLabel();
        Button_preview = new javax.swing.JButton();
        Button_exit = new javax.swing.JButton();
        Label_change = new javax.swing.JLabel();
        TextField_cash = new javax.swing.JTextField();
        TextField_change = new javax.swing.JTextField();
        Label_totalprice = new javax.swing.JLabel();
        TextField_mem = new javax.swing.JTextField();
        Label_mem = new javax.swing.JLabel();
        Panel_Bev = new javax.swing.JPanel();
        Button_Bev_back = new javax.swing.JButton();
        Button_hot_cappu = new javax.swing.JButton();
        Label_coffee = new javax.swing.JLabel();
        Button_hot_esp = new javax.swing.JButton();
        Button_hot_latte = new javax.swing.JButton();
        Label_non = new javax.swing.JLabel();
        Button_hot_cocoa = new javax.swing.JButton();
        Button_hot_milk = new javax.swing.JButton();
        Button_hot_thaitea = new javax.swing.JButton();
        Label_smoothie = new javax.swing.JLabel();
        Button_fs_lemon = new javax.swing.JButton();
        Button_fs_orange = new javax.swing.JButton();
        Button_fs_banana = new javax.swing.JButton();
        Panel_bake = new javax.swing.JPanel();
        Button_Bak_back = new javax.swing.JButton();
        Button_cake_vanilla = new javax.swing.JButton();
        Label_bakery = new javax.swing.JLabel();
        Button_cake_crape = new javax.swing.JButton();
        Button_cake_choco = new javax.swing.JButton();
        Button_cake_straw = new javax.swing.JButton();
        Button_cake_white = new javax.swing.JButton();
        Button_cookies = new javax.swing.JButton();
        Panel_Etc = new javax.swing.JPanel();
        Button_Etc_back = new javax.swing.JButton();
        Button_spaghet_tomato = new javax.swing.JButton();
        Label_etc = new javax.swing.JLabel();
        Button_spaghet_white = new javax.swing.JButton();
        Button_spaghet_spicy = new javax.swing.JButton();
        Button_steak_chic = new javax.swing.JButton();
        Button_steak_pork = new javax.swing.JButton();
        Button_frenchfries = new javax.swing.JButton();
        TextField_emp = new javax.swing.JTextField();
        TextField_date = new javax.swing.JTextField();
        TextField_time = new javax.swing.JTextField();
        TextField_cus = new javax.swing.JTextField();
        Label_cus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_time.setText("Time:");

        Label_date.setText("Date:");

        Label_emp.setText("Employee:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Button_Bev.setText("Beverages");
        Button_Bev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BevActionPerformed(evt);
            }
        });

        Button_Bake.setText("Bakery");
        Button_Bake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BakeActionPerformed(evt);
            }
        });

        Button_Etc.setText("Etc.");
        Button_Etc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EtcActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Button_cancelorder.setText("cancel order");
        Button_cancelorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Button_Bev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Bake, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Etc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_cancelorder)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Bev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Bake, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Etc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_cancelorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layeredpane.setLayout(new java.awt.CardLayout());

        Panel_cal.setBackground(new java.awt.Color(204, 204, 255));

        Button_7.setText("7");
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_8.setText("8");
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_9.setText("9");
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_4.setText("4");
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_5.setText("5");
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_6.setText("6");
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_1.setText("1");
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_2.setText("2");
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_3.setText("3");
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        Button_0.setText("0");
        Button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_0ActionPerformed(evt);
            }
        });

        Button_00.setText("00");
        Button_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_00ActionPerformed(evt);
            }
        });

        Button_dot.setText(".");
        Button_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_dotActionPerformed(evt);
            }
        });

        Button_equal.setText("รับพอดี");
        Button_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_equalActionPerformed(evt);
            }
        });

        Button_backspace.setText("backspace");
        Button_backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backspaceActionPerformed(evt);
            }
        });

        Button_clear.setText("clear");
        Button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_clearActionPerformed(evt);
            }
        });

        Button_payment.setText("payment");
        Button_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_paymentActionPerformed(evt);
            }
        });

        Label_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_price.setText("ยอดรวม");

        Label_cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_cash.setText("ยอดที่รับมา");

        Button_preview.setText("Preview");
        Button_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_previewActionPerformed(evt);
            }
        });

        Button_exit.setText("X");
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        Label_change.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_change.setText("เงินทอน");

        TextField_cash.setEditable(false);
        TextField_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_cashActionPerformed(evt);
            }
        });

        TextField_change.setEditable(false);
        TextField_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_changeActionPerformed(evt);
            }
        });

        TextField_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_memActionPerformed(evt);
            }
        });

        Label_mem.setText("Member:");

        javax.swing.GroupLayout Panel_calLayout = new javax.swing.GroupLayout(Panel_cal);
        Panel_cal.setLayout(Panel_calLayout);
        Panel_calLayout.setHorizontalGroup(
            Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_calLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_calLayout.createSequentialGroup()
                        .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_calLayout.createSequentialGroup()
                                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_00, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                            .addGroup(Panel_calLayout.createSequentialGroup()
                                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(Button_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(Button_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Button_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_calLayout.createSequentialGroup()
                        .addComponent(Label_change)
                        .addGap(102, 102, 102)
                        .addComponent(TextField_change))
                    .addGroup(Panel_calLayout.createSequentialGroup()
                        .addComponent(Button_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_exit))
                    .addGroup(Panel_calLayout.createSequentialGroup()
                        .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Label_mem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_cash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_price, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_calLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(Label_totalprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Panel_calLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_cash)
                                    .addComponent(TextField_mem, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        Panel_calLayout.setVerticalGroup(
            Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_calLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_mem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_mem))
                .addGap(18, 18, 18)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_price)
                    .addComponent(Label_totalprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_cash)
                    .addComponent(TextField_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_change)
                    .addComponent(TextField_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_00, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_calLayout.createSequentialGroup()
                        .addComponent(Button_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(Button_preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layeredpane.add(Panel_cal, "card2");

        Panel_Bev.setBackground(new java.awt.Color(204, 204, 255));
        Panel_Bev.setPreferredSize(new java.awt.Dimension(294, 395));

        Button_Bev_back.setText("back");
        Button_Bev_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Bev_backActionPerformed(evt);
            }
        });

        Button_hot_cappu.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Button_hot_cappu.setText("Hot Cappucino");
        Button_hot_cappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_cappuActionPerformed(evt);
            }
        });

        Label_coffee.setText("Coffee");

        Button_hot_esp.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Button_hot_esp.setText("Hot Espresso");
        Button_hot_esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_espActionPerformed(evt);
            }
        });

        Button_hot_latte.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Button_hot_latte.setText("Hot Latte");
        Button_hot_latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_latteActionPerformed(evt);
            }
        });

        Label_non.setText("Non-Coffee");

        Button_hot_cocoa.setText("Hot Cocoa");
        Button_hot_cocoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_cocoaActionPerformed(evt);
            }
        });

        Button_hot_milk.setText("Hot Milk");
        Button_hot_milk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_milkActionPerformed(evt);
            }
        });

        Button_hot_thaitea.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Button_hot_thaitea.setText("Hot Thai tea");
        Button_hot_thaitea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hot_thaiteaActionPerformed(evt);
            }
        });

        Label_smoothie.setText("Smoothie");

        Button_fs_lemon.setText("FS- Lemon");
        Button_fs_lemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_fs_lemonActionPerformed(evt);
            }
        });

        Button_fs_orange.setText("FS-Orange");
        Button_fs_orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_fs_orangeActionPerformed(evt);
            }
        });

        Button_fs_banana.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Button_fs_banana.setText("Banana Smoothie");
        Button_fs_banana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_fs_bananaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BevLayout = new javax.swing.GroupLayout(Panel_Bev);
        Panel_Bev.setLayout(Panel_BevLayout);
        Panel_BevLayout.setHorizontalGroup(
            Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BevLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Bev_back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BevLayout.createSequentialGroup()
                        .addComponent(Button_hot_cappu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_hot_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_hot_latte, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BevLayout.createSequentialGroup()
                        .addComponent(Button_hot_cocoa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_hot_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_hot_thaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BevLayout.createSequentialGroup()
                        .addComponent(Button_fs_lemon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_fs_orange, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_fs_banana, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BevLayout.createSequentialGroup()
                        .addGroup(Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_BevLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(Label_coffee))
                            .addGroup(Panel_BevLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(Label_smoothie))
                            .addGroup(Panel_BevLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(Label_non)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_BevLayout.setVerticalGroup(
            Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BevLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Label_coffee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_hot_cappu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_hot_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_hot_latte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_non)
                .addGap(5, 5, 5)
                .addGroup(Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_hot_cocoa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_hot_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_hot_thaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_smoothie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_BevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_fs_lemon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_fs_orange, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_fs_banana, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Bev_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        layeredpane.add(Panel_Bev, "card4");

        Panel_bake.setBackground(new java.awt.Color(204, 204, 255));
        Panel_bake.setPreferredSize(new java.awt.Dimension(294, 395));

        Button_Bak_back.setText("back");
        Button_Bak_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Bak_backActionPerformed(evt);
            }
        });

        Button_cake_vanilla.setText("Vanilla cake");
        Button_cake_vanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cake_vanillaActionPerformed(evt);
            }
        });

        Label_bakery.setText("Bakery");

        Button_cake_crape.setText("Crape cake");
        Button_cake_crape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cake_crapeActionPerformed(evt);
            }
        });

        Button_cake_choco.setText("Choco cake");
        Button_cake_choco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cake_chocoActionPerformed(evt);
            }
        });

        Button_cake_straw.setText("Strawberries cake");
        Button_cake_straw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cake_strawActionPerformed(evt);
            }
        });

        Button_cake_white.setText("White cake");
        Button_cake_white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cake_whiteActionPerformed(evt);
            }
        });

        Button_cookies.setText("Cookies");
        Button_cookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cookiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_bakeLayout = new javax.swing.GroupLayout(Panel_bake);
        Panel_bake.setLayout(Panel_bakeLayout);
        Panel_bakeLayout.setHorizontalGroup(
            Panel_bakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_bakeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_bakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_bakeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Bak_back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_bakeLayout.createSequentialGroup()
                        .addComponent(Button_cake_vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_cake_crape, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_cake_choco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_bakeLayout.createSequentialGroup()
                        .addComponent(Button_cake_straw, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_cake_white, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_cookies, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_bakeLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Label_bakery)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_bakeLayout.setVerticalGroup(
            Panel_bakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_bakeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Label_bakery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_bakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_cake_vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_cake_crape, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_cake_choco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_bakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_cake_straw, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_cake_white, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_cookies, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Bak_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        layeredpane.add(Panel_bake, "card3");

        Panel_Etc.setBackground(new java.awt.Color(204, 204, 255));
        Panel_Etc.setPreferredSize(new java.awt.Dimension(294, 395));

        Button_Etc_back.setText("back");
        Button_Etc_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Etc_backActionPerformed(evt);
            }
        });

        Button_spaghet_tomato.setText("Spaghetti Tomato");
        Button_spaghet_tomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_spaghet_tomatoActionPerformed(evt);
            }
        });

        Label_etc.setText("Etc.");

        Button_spaghet_white.setText("Spaghetti White");
        Button_spaghet_white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_spaghet_whiteActionPerformed(evt);
            }
        });

        Button_spaghet_spicy.setText("Spaghetti Spicy");
        Button_spaghet_spicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_spaghet_spicyActionPerformed(evt);
            }
        });

        Button_steak_chic.setText("Chicken steak");
        Button_steak_chic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_steak_chicActionPerformed(evt);
            }
        });

        Button_steak_pork.setText("Pork steak");
        Button_steak_pork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_steak_porkActionPerformed(evt);
            }
        });

        Button_frenchfries.setText("French fires");
        Button_frenchfries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_frenchfriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_EtcLayout = new javax.swing.GroupLayout(Panel_Etc);
        Panel_Etc.setLayout(Panel_EtcLayout);
        Panel_EtcLayout.setHorizontalGroup(
            Panel_EtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EtcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_EtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_EtcLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Etc_back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EtcLayout.createSequentialGroup()
                        .addComponent(Button_spaghet_tomato, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_spaghet_white, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_spaghet_spicy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EtcLayout.createSequentialGroup()
                        .addComponent(Button_steak_chic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_steak_pork, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_frenchfries, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EtcLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Label_etc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_EtcLayout.setVerticalGroup(
            Panel_EtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_EtcLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Label_etc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_EtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_spaghet_tomato, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_spaghet_white, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_spaghet_spicy, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_EtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_steak_chic, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_steak_pork, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_frenchfries, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Etc_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        layeredpane.add(Panel_Etc, "card5");

        TextField_emp.setEditable(false);
        TextField_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_empActionPerformed(evt);
            }
        });

        TextField_date.setEditable(false);
        TextField_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_dateActionPerformed(evt);
            }
        });

        TextField_time.setEditable(false);

        TextField_cus.setEditable(false);

        Label_cus.setText("Customer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_cus)
                        .addGap(21, 21, 21)
                        .addComponent(TextField_cus))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label_date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_time, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(layeredpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextField_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_cus)
                                .addComponent(TextField_cus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Label_date)
                                .addComponent(Label_time)
                                .addComponent(Label_emp)
                                .addComponent(TextField_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(403, 403, 403))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(layeredpane)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BevActionPerformed
        setPane(Panel_Bev);
    }//GEN-LAST:event_Button_BevActionPerformed

    private void Button_BakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BakeActionPerformed
        setPane(Panel_bake);
    }//GEN-LAST:event_Button_BakeActionPerformed

    private void Button_EtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EtcActionPerformed
        setPane(Panel_Etc);
    }//GEN-LAST:event_Button_EtcActionPerformed

    private void Button_Bak_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Bak_backActionPerformed
        setPane(Panel_cal);
    }//GEN-LAST:event_Button_Bak_backActionPerformed

    private void Button_Bev_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Bev_backActionPerformed
        setPane(Panel_cal);
    }//GEN-LAST:event_Button_Bev_backActionPerformed

    private void Button_Etc_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Etc_backActionPerformed
        setPane(Panel_cal);
    }//GEN-LAST:event_Button_Etc_backActionPerformed

    private void Button_hot_cappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_cappuActionPerformed
        menuid = "M001";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_hot_cappuActionPerformed

    private void Button_hot_espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_espActionPerformed
        menuid = "M002";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();

    }//GEN-LAST:event_Button_hot_espActionPerformed

    private void Button_cancelorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelorderActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure to cancel this order?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            clear();
        }
    }//GEN-LAST:event_Button_cancelorderActionPerformed

    private void Button_hot_latteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_latteActionPerformed
        menuid = "M003";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_hot_latteActionPerformed

    private void TextField_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_dateActionPerformed

    }//GEN-LAST:event_TextField_dateActionPerformed

    private void TextField_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_empActionPerformed

    private void Button_hot_cocoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_cocoaActionPerformed
        menuid = "M004";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_hot_cocoaActionPerformed

    private void Button_hot_milkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_milkActionPerformed
        menuid = "M009";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_hot_milkActionPerformed

    private void Button_hot_thaiteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hot_thaiteaActionPerformed
        menuid = "M005";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_hot_thaiteaActionPerformed

    private void Button_fs_lemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_fs_lemonActionPerformed
        menuid = "M036";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_fs_lemonActionPerformed

    private void Button_fs_orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_fs_orangeActionPerformed
        menuid = "M037";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_fs_orangeActionPerformed

    private void Button_fs_bananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_fs_bananaActionPerformed
        menuid = "M039";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_fs_bananaActionPerformed

    private void Button_cake_vanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cake_vanillaActionPerformed
        menuid = "M041";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cake_vanillaActionPerformed

    private void Button_cake_crapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cake_crapeActionPerformed
        menuid = "M042";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cake_crapeActionPerformed

    private void Button_cake_chocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cake_chocoActionPerformed
        menuid = "M043";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cake_chocoActionPerformed

    private void Button_cake_strawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cake_strawActionPerformed
        menuid = "M044";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cake_strawActionPerformed

    private void Button_cake_whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cake_whiteActionPerformed
        menuid = "M045";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cake_whiteActionPerformed

    private void Button_cookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cookiesActionPerformed
        menuid = "M046";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_cookiesActionPerformed

    private void Button_spaghet_tomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_spaghet_tomatoActionPerformed
        menuid = "M056";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_spaghet_tomatoActionPerformed

    private void Button_spaghet_whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_spaghet_whiteActionPerformed
        menuid = "M057";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_spaghet_whiteActionPerformed

    private void Button_spaghet_spicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_spaghet_spicyActionPerformed
        menuid = "M058";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_spaghet_spicyActionPerformed

    private void Button_steak_chicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_steak_chicActionPerformed
        menuid = "M059";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_steak_chicActionPerformed

    private void Button_steak_porkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_steak_porkActionPerformed
        menuid = "M060";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_steak_porkActionPerformed

    private void Button_frenchfriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_frenchfriesActionPerformed
        menuid = "M062";
        DBObject ol_id = new BasicDBObject();
        ol_id.put("MS_Menu_Id", menuid);
        list.add(ol_id);
        setTable();
    }//GEN-LAST:event_Button_frenchfriesActionPerformed

    private void TextField_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_memActionPerformed
        cusphone = TextField_mem.getText();
        try{
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Customer");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();

            searchQuery.put("MS_Customer_Phone", cusphone);
            DBCursor cursor = table.find(searchQuery);
            while (cursor.hasNext()) {
                //System.out.println(cursor.next());
                DBObject obj = cursor.next();
                cname = (String) obj.get("MS_Customer_Fname");
                cid = (String) obj.get("MS_Customer_Id");
                //cname = cname+(String)obj.get("MS_Customer_Id");
                System.out.println(cname);
                break;
            }
        }catch(Exception e){

        }
        TextField_cus.setText(cname+"("+cid+")");
        Label_price.requestFocus();
    }//GEN-LAST:event_TextField_memActionPerformed

    private void TextField_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_changeActionPerformed

    private void TextField_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_cashActionPerformed
        my_price = TextField_cash.getText();
    }//GEN-LAST:event_TextField_cashActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Button_exitActionPerformed

    private void Button_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_previewActionPerformed
        if (check2 == true) {
            try {

                Document doc = new Document();
                String filename = "inv" + useror + ".pdf";
                PdfWriter.getInstance(doc, new FileOutputStream("d:/invoice/" + filename));

                doc.open();
                doc.add(new Paragraph(String.format("                     Inthanin Billing\n"
                    + "---------------------------------------------------------\n"
                    + "Customer: " + cid + " Name: "+ cname +" Phone No: "+ cusphone + "      Employee: " + empid
                    + "\nOrder ID: " + useror + "          " + "Date: " + date
                    + "\n---------------------------------------------------------\n"), normal));
        for (ord a : arr) {
            doc.add(new Paragraph((a.toString()), normal));
            System.out.println(a.toString());
        }
        doc.add(new Paragraph(("\n---------------------------------------------------------\n"), normal));
        doc.add(new Paragraph(String.format("Total:                                " + price_total + " Baht"
            + "\nCash:                                " + ur_price + " Baht" + "\nChange:                                " + last_price
            + " Baht" + "\n---------------------------------------------------------\n"), normal));
doc.add(new Paragraph(String.format("                         " + "Thank You :)\n"), normal));

doc.close();

Desktop.getDesktop().open(new File("d:/invoice/" + filename));
} catch (Exception e) {

    }
    System.out.println("OK, can print");
    clear();
    } else {
        JOptionPane.showMessageDialog(this, "Please payment before print an invoice.");
        }
    }//GEN-LAST:event_Button_previewActionPerformed

    private void Button_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_paymentActionPerformed

        if (!my_price.isEmpty()) {
            cal();
            System.out.println(list);
            Button_preview.requestFocus();
            check2 = true;
        } else {
            JOptionPane.showMessageDialog(this, "Please recieve the money from customer");
        }
    }//GEN-LAST:event_Button_paymentActionPerformed

    private void Button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_clearActionPerformed
        TextField_cash.setText("");
        my_price = "";
        TextField_change.setText("");
    }//GEN-LAST:event_Button_clearActionPerformed

    private void Button_backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backspaceActionPerformed
        if (my_price != null && my_price.length() > 0) {
            my_price = my_price.substring(0, my_price.length() - 1);
            TextField_cash.setText(my_price);
        }
    }//GEN-LAST:event_Button_backspaceActionPerformed

    private void Button_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_equalActionPerformed
        TextField_cash.setText(settp);
        my_price = settp;
        check1 = true;
    }//GEN-LAST:event_Button_equalActionPerformed

    private void Button_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_dotActionPerformed
        my_price = my_price + ".";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_dotActionPerformed

    private void Button_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_00ActionPerformed
        my_price = my_price + "00";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_00ActionPerformed

    private void Button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_0ActionPerformed
        my_price = my_price + "0";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_0ActionPerformed

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
        my_price = my_price + "3";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        my_price = my_price + "2";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed
        my_price = my_price + "1";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        my_price = my_price + "6";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
        my_price = my_price + "5";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
        my_price = my_price + "4";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        my_price = my_price + "9";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        my_price = my_price + "8";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
        my_price = my_price + "7";
        TextField_cash.setText(my_price);
    }//GEN-LAST:event_Button_7ActionPerformed

    public void clear() {
        try {
            TextField_cash.setText("");
            TextField_change.setText("");
            arr.clear();
            model.setRowCount(0);
            jTable1.setModel(model);
            menuid = "";
            countno = 1;
            price_total = 0;
            Label_totalprice.setText("");
            my_price = "";
            ur_price = 0;
            settp = "";
            cname = "";
            cusphone = "";
            cid = "";
            TextField_mem.setText("");
            TextField_cus.setText("");

        } catch (Exception e) {

        }
    }

    public void cal() {
        ur_price = Double.valueOf(my_price);
        if (ur_price < price_total) {
            JOptionPane.showMessageDialog(null, "Not enough money to pay this order.");
            TextField_cash.setText("");
            ur_price = 0;
            my_price = "";
        } else if (ur_price != price_total) {
            last_price = ur_price - price_total;
            String lastly_price = String.valueOf(last_price);
            TextField_change.setText(lastly_price);
            if (cid == null) {
                cid = "C000";
            }
            System.out.println(cid);
            getUsername();
            getOL();
        } else {
            last_price = 0;
            String lastly_price = String.valueOf(last_price);
            TextField_change.setText(lastly_price);
            if (cid == null) {
                cid = "C000";
            }
            System.out.println(cid);
            getUsername();
            getOL();
        }

    }

    private static void getUsername() {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Order_List");
            BasicDBObject searchQuery = new BasicDBObject();
            DBCursor cursor = table.find();
            count = cursor.count();
        } catch (UnknownHostException e) {
        }
        if (count > 99 || count == 99) {
            username = "OL" + (count + 1);
        } else if (count > 9 || count == 9) {
            username = "OL0" + (count + 1);
        } else {
            username = "OL00" + (count + 1);
        }
        System.out.println(username);
    }

    private static void getUserOrder() {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Order");
            BasicDBObject searchQuery = new BasicDBObject();
            DBCursor cursor = table.find();
            count = cursor.count();
        } catch (Exception e) {
        }
        if (count > 99 || count == 99) {
            useror = "O" + (count + 1);
        } else if (count > 9 || count == 9) {
            useror = "O0" + (count + 1);
        } else {
            useror = "O00" + (count + 1);
        }
        System.out.println(useror);
    }

    public void getOL() {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Order_List");
            BasicDBObject document = new BasicDBObject();
            getUsername();
            document.put("TRN_Order_List_Id", username);
            document.put("MS_Menu_Id", list);
            table.insert(document);
            System.out.println("can get ol");
            getOrder(username);
        } catch (Exception e) {

        }
    }

    public void getOrder(String username) {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("TRN_Order");
            BasicDBObject document = new BasicDBObject();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM dd, yyyy HH:mm:ss a");
            LocalDateTime now = LocalDateTime.now();
            date = dtf.format(now);

            getUserOrder();
            document.put("TRN_Order_Id", useror);
            document.put("TRN_Order_Date", date);
            document.put("TRN_Order_totalprice", price_total);
            document.put("MS_Customer_Id", cid);
            document.put("MS_Employee_Id", empid);
            document.put("TRN_Order_List_Id", username);
            table.insert(document);

            System.out.println("can get order");
        } catch (Exception e) {

        }
    }

    public void setTable() {
        try {

            MongoClient mongo = new MongoClient("localhost", 27017);

            DB db = mongo.getDB("inthanin");

            DBCollection coll = db.getCollection("MS_Menu");
            BasicDBObject searchQuery = new BasicDBObject();

            searchQuery.put("MS_Menu_Id", menuid);
            DBCursor cursor = coll.find(searchQuery);

            while (cursor.hasNext()) {
                DBObject obj = cursor.next();
                countno += model.getRowCount();
                String num = String.valueOf(countno);
                String id = (String) obj.get("MS_Menu_Id");
                String name = (String) obj.get("MS_Menu_Name");
                String price = (String) obj.get("MS_Menu_Price");
                String type = (String) obj.get("MS_Menu_Type");
                model.addRow(new Object[]{num, id, name, price, type});

                arr.add(new ord(id, name, Double.parseDouble(price)));

                countno = 1;
                price_total += Double.valueOf(price);
                settp = String.valueOf(price_total);
                Label_totalprice.setText(settp);
            }
            for (ord a : arr) {
                System.out.println(a.toString());
            }
            jTable1.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {

                    JTable target = (JTable) e.getSource();

                    int selectedRow = target.getSelectedRow();
                    int selectedColumn = target.getSelectedColumn();

                    System.out.println("Selected row " + " " + selectedRow);
                    System.out.println("Selected column" + " " + selectedColumn);

                    Object selectedCellValue = target.getValueAt(selectedRow, selectedColumn);
                    pid = (String) selectedCellValue;
                    System.out.println("selectedCellValue " + " " + pid);

                }
            }
        });
    }

    public void getTime() {
        Date d = new Date();
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("HH:mm:ss");
                SimpleDateFormat t = new SimpleDateFormat("YYYY-MM-dd");
                TextField_date.setText(t.format(d));
                TextField_time.setText(s.format(d));
            }
        }).start();

    }

    public void getid(String id, String loginid) {
        empid = id;
        logid = loginid;
        System.out.println(empid + " " + logid);
        getemp();

    }

    public void getemp() {

        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Employee");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();
            searchQuery.put("MS_Employee_Id", empid);
            DBCursor cursor = table.find(searchQuery);
            if (cursor.hasNext() == true) {
                for (DBObject a : cursor) {
                    System.out.println(cursor.next());
                    String fname = (String) a.get("MS_Employee_Fname");
                    String lname = (String) a.get("MS_Employee_Lname");
                    type = (String) a.get("MS_Employee_Type");
                    name = lname + " " + fname + " (" + type + ")";
                    TextField_emp.setText(name);
                }
            } else {
                System.out.println("Please select id");
            }

        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_0;
    private javax.swing.JButton Button_00;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JButton Button_Bak_back;
    private javax.swing.JButton Button_Bake;
    private javax.swing.JButton Button_Bev;
    private javax.swing.JButton Button_Bev_back;
    private javax.swing.JButton Button_Etc;
    private javax.swing.JButton Button_Etc_back;
    private javax.swing.JButton Button_backspace;
    private javax.swing.JButton Button_cake_choco;
    private javax.swing.JButton Button_cake_crape;
    private javax.swing.JButton Button_cake_straw;
    private javax.swing.JButton Button_cake_vanilla;
    private javax.swing.JButton Button_cake_white;
    private javax.swing.JButton Button_cancelorder;
    private javax.swing.JButton Button_clear;
    private javax.swing.JButton Button_cookies;
    private javax.swing.JButton Button_dot;
    private javax.swing.JButton Button_equal;
    private javax.swing.JButton Button_exit;
    private javax.swing.JButton Button_frenchfries;
    private javax.swing.JButton Button_fs_banana;
    private javax.swing.JButton Button_fs_lemon;
    private javax.swing.JButton Button_fs_orange;
    private javax.swing.JButton Button_hot_cappu;
    private javax.swing.JButton Button_hot_cocoa;
    private javax.swing.JButton Button_hot_esp;
    private javax.swing.JButton Button_hot_latte;
    private javax.swing.JButton Button_hot_milk;
    private javax.swing.JButton Button_hot_thaitea;
    private javax.swing.JButton Button_payment;
    private javax.swing.JButton Button_preview;
    private javax.swing.JButton Button_spaghet_spicy;
    private javax.swing.JButton Button_spaghet_tomato;
    private javax.swing.JButton Button_spaghet_white;
    private javax.swing.JButton Button_steak_chic;
    private javax.swing.JButton Button_steak_pork;
    private javax.swing.JLabel Label_bakery;
    private javax.swing.JLabel Label_cash;
    private javax.swing.JLabel Label_change;
    private javax.swing.JLabel Label_coffee;
    private javax.swing.JLabel Label_cus;
    private javax.swing.JLabel Label_date;
    private javax.swing.JLabel Label_emp;
    private javax.swing.JLabel Label_etc;
    private javax.swing.JLabel Label_mem;
    private javax.swing.JLabel Label_non;
    private javax.swing.JLabel Label_price;
    private javax.swing.JLabel Label_smoothie;
    private javax.swing.JLabel Label_time;
    private javax.swing.JLabel Label_totalprice;
    private javax.swing.JPanel Panel_Bev;
    private javax.swing.JPanel Panel_Etc;
    private javax.swing.JPanel Panel_bake;
    private javax.swing.JPanel Panel_cal;
    private javax.swing.JTextField TextField_cash;
    private javax.swing.JTextField TextField_change;
    private javax.swing.JTextField TextField_cus;
    private javax.swing.JTextField TextField_date;
    private javax.swing.JTextField TextField_emp;
    private javax.swing.JTextField TextField_mem;
    private javax.swing.JTextField TextField_time;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLayeredPane layeredpane;
    // End of variables declaration//GEN-END:variables
}
