/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.JOptionPane;

/**
 *
 * @author madmm
 */
public class Product_Edit extends javax.swing.JFrame {

    /**
     * Creates new form Product_Add
     */
    public Product_Edit() {
        initComponents();
    }

    static String username;
    static String newusername;
    static boolean Foundname;
    static long count;
    static String name;
    static String unit;
    static String price;
    static String type;
    static String newname;
    static String newunit;
    static String newprice;
    static String newtype;

    public void getpid(String pid) {
        username = pid;
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Product");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();

            searchQuery.put("MS_Product_Id", username);
            DBCursor cursor = table.find(searchQuery);
            if (cursor.hasNext() == true) {
                for (DBObject a : cursor) {
                    System.out.println(cursor.next());
                    name = (String) a.get("MS_Product_Name");
                    unit = (String) a.get("MS_Product_Unit");
                    price = (String) a.get("MS_Product_Price");
                    type = (String) a.get("MS_Product_Type");
                    System.out.println(username+ name + unit + price + type);
                    TextField_id.setText(username);
                    TextField_name.setText(name);
                    TextField_unit.setText(unit);
                    TextField_price.setText(price);
                    TextField_type.setText(type);

                }
            } else {
                System.out.println("Please select id");
                JOptionPane.showMessageDialog(this, "Please select Id column.");
                this.setVisible(false);
            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_head = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextField_name = new javax.swing.JTextField();
        Label_name = new javax.swing.JLabel();
        Button_edit = new javax.swing.JButton();
        Button_exit = new javax.swing.JButton();
        Label_unit = new javax.swing.JLabel();
        TextField_unit = new javax.swing.JTextField();
        Label_price = new javax.swing.JLabel();
        TextField_price = new javax.swing.JTextField();
        Label_type = new javax.swing.JLabel();
        TextField_type = new javax.swing.JTextField();
        Label_id = new javax.swing.JLabel();
        TextField_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_head.setText("Edit a Product");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        TextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_nameActionPerformed(evt);
            }
        });

        Label_name.setText("Product Name");

        Button_edit.setText("Edit");
        Button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_editActionPerformed(evt);
            }
        });

        Button_exit.setText("Cancel");
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        Label_unit.setText("Product Unit");

        TextField_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_unitActionPerformed(evt);
            }
        });

        Label_price.setText("Product Price");

        TextField_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_priceActionPerformed(evt);
            }
        });

        Label_type.setText("Product Type");

        TextField_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_typeActionPerformed(evt);
            }
        });

        Label_id.setText("Product Id");

        TextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_name)
                            .addComponent(TextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_unit)
                            .addComponent(TextField_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(Button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_price)
                                    .addComponent(TextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_type, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_type)))
                            .addComponent(Label_id)
                            .addComponent(TextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Label_name)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Label_unit)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_price)
                    .addComponent(Label_type))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_id)
                .addGap(8, 8, 8)
                .addComponent(TextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Label_head)
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Label_head)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_nameActionPerformed

        newname = TextField_name.getText();
        TextField_unit.requestFocus();
    }//GEN-LAST:event_TextField_nameActionPerformed

    private void TextField_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_unitActionPerformed

        newunit = TextField_unit.getText();
        TextField_price.requestFocus();
    }//GEN-LAST:event_TextField_unitActionPerformed

    private void TextField_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_priceActionPerformed

        newprice = TextField_price.getText();
        TextField_type.requestFocus();
    }//GEN-LAST:event_TextField_priceActionPerformed

    private void TextField_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_typeActionPerformed

        newtype = TextField_type.getText();
        TextField_id.requestFocus();
    }//GEN-LAST:event_TextField_typeActionPerformed

    private void TextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_idActionPerformed

        newusername = TextField_id.getText();
        Button_edit.requestFocus();
    }//GEN-LAST:event_TextField_idActionPerformed

    private void Button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_editActionPerformed
        try {
            if(TextField_id.toString().equals(""))
                TextField_id.setText(username);
            if(TextField_name.toString().equals(""))
                TextField_name.setText(name);
            if(TextField_unit.toString().equals(""))
                TextField_unit.setText(unit);
            if(TextField_price.toString().equals(""))
                TextField_price.setText(price);
            if(TextField_type.toString().equals(""))
                TextField_type.setText(type);
            
            MongoClient mongo = new MongoClient("localhost", 27017);

            DB db = mongo.getDB("inthanin");

            DBCollection coll = db.getCollection("MS_Product");

            BasicDBObject newDocument = new BasicDBObject();

            DBObject query = new BasicDBObject().append("MS_Product_Id", username);
            System.out.println(newusername);
            newDocument.append("$set", new BasicDBObject().append("MS_Product_Id", newusername));

            coll.update(query, newDocument);

            DBObject query2 = new BasicDBObject().append("MS_Product_Name", name);
            System.out.println(newname);
            newDocument.append("$set", new BasicDBObject().append("MS_Product_Name", newname));

            coll.update(query2, newDocument);

            DBObject query3 = new BasicDBObject().append("MS_Product_Unit", unit);
            System.out.println(newunit);
            newDocument.append("$set", new BasicDBObject().append("MS_Product_Unit", newunit));

            coll.update(query3, newDocument);

            DBObject query4 = new BasicDBObject().append("MS_Product_Price", price);
            System.out.println(newprice);
            newDocument.append("$set", new BasicDBObject().append("MS_Product_Price", newprice));

            coll.update(query4, newDocument);

            DBObject query5 = new BasicDBObject().append("MS_Product_Type", type);
            System.out.println(newtype);
            newDocument.append("$set", new BasicDBObject().append("MS_Product_Type", newtype));

            coll.update(query5, newDocument);
            JOptionPane.showMessageDialog(this, "Update now.");

        } catch (Exception e) {

        }
        this.setVisible(false);
    }//GEN-LAST:event_Button_editActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Button_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_edit;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_head;
    private javax.swing.JLabel Label_id;
    private javax.swing.JLabel Label_name;
    private javax.swing.JLabel Label_price;
    private javax.swing.JLabel Label_type;
    private javax.swing.JLabel Label_unit;
    private javax.swing.JTextField TextField_id;
    private javax.swing.JTextField TextField_name;
    private javax.swing.JTextField TextField_price;
    private javax.swing.JTextField TextField_type;
    private javax.swing.JTextField TextField_unit;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
