/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import javax.swing.JOptionPane;

/**
 *
 * @author madmm
 */
public class Sign extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    static String username;
    static String Fname;
    static String Lname;
    static String Address_total;
    static String Address1;
    static String Address2;
    static String Address3;
    static String Address4;
    static String Address5;
    static String In;
    static String pno;
    static String birth;
    static String type;
    static String gender;
    static String age;
    static String password;
    static String position;
    static long count = 0;
    static boolean FoundIn;

    public Sign() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        TextField_fname = new javax.swing.JTextField();
        Label_fname = new javax.swing.JLabel();
        Label_sir = new javax.swing.JLabel();
        TextField_sir = new javax.swing.JTextField();
        TextField_add = new javax.swing.JTextField();
        Label_Add = new javax.swing.JLabel();
        Label_Subdist = new javax.swing.JLabel();
        TextField_subdist = new javax.swing.JTextField();
        Label_prov = new javax.swing.JLabel();
        TextField_prov = new javax.swing.JTextField();
        Label_ID = new javax.swing.JLabel();
        TextField_ID = new javax.swing.JTextField();
        Label_phone = new javax.swing.JLabel();
        TextField_phone = new javax.swing.JTextField();
        Label_bd = new javax.swing.JLabel();
        TextField_bd = new javax.swing.JTextField();
        TextField_dist = new javax.swing.JTextField();
        Label_dist = new javax.swing.JLabel();
        TextField_post = new javax.swing.JTextField();
        Label_post = new javax.swing.JLabel();
        Label_gender = new javax.swing.JLabel();
        TextField_gender = new javax.swing.JTextField();
        Label_age = new javax.swing.JLabel();
        TextField_age = new javax.swing.JTextField();
        Label_password = new javax.swing.JLabel();
        TextField_password = new javax.swing.JTextField();
        Label_posion = new javax.swing.JLabel();
        TextField_position = new javax.swing.JTextField();
        Label_create = new javax.swing.JLabel();
        Button_ok = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        TextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_fnameActionPerformed(evt);
            }
        });

        Label_fname.setText("First Name");

        Label_sir.setText("Sirname");

        TextField_sir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_sirActionPerformed(evt);
            }
        });

        TextField_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_addActionPerformed(evt);
            }
        });

        Label_Add.setText("Address");

        Label_Subdist.setText("Sub District");

        TextField_subdist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_subdistActionPerformed(evt);
            }
        });

        Label_prov.setText("Province");

        TextField_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_provActionPerformed(evt);
            }
        });

        Label_ID.setText("Identified ");

        TextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_IDActionPerformed(evt);
            }
        });

        Label_phone.setText("Phone Number");

        TextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_phoneActionPerformed(evt);
            }
        });

        Label_bd.setText("Birth Date");

        TextField_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_bdActionPerformed(evt);
            }
        });

        TextField_dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_distActionPerformed(evt);
            }
        });

        Label_dist.setText("District");

        TextField_post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_postActionPerformed(evt);
            }
        });

        Label_post.setText("Postal Code");

        Label_gender.setText("Gender");

        TextField_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_genderActionPerformed(evt);
            }
        });

        Label_age.setText("Age");

        TextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ageActionPerformed(evt);
            }
        });

        Label_password.setText("Password");

        TextField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_passwordActionPerformed(evt);
            }
        });

        Label_posion.setText("Position");

        TextField_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_positionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_age)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_fname)
                            .addComponent(TextField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_sir)
                            .addComponent(TextField_sir, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Label_Add)
                    .addComponent(TextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Subdist)
                            .addComponent(TextField_subdist, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_dist)
                            .addComponent(TextField_dist, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_prov)
                            .addComponent(TextField_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_post)
                            .addComponent(TextField_post, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_ID)
                            .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_phone)
                            .addComponent(TextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_bd)
                            .addComponent(TextField_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_gender)
                            .addComponent(TextField_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_password)))
                    .addComponent(Label_posion)
                    .addComponent(TextField_position, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Label_fname)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Label_sir)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_sir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Label_Add)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(TextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Label_Subdist)
                                                .addGap(8, 8, 8)
                                                .addComponent(TextField_subdist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(Label_dist)
                                                .addGap(8, 8, 8)
                                                .addComponent(TextField_dist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_prov)
                                        .addGap(8, 8, 8)
                                        .addComponent(TextField_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Label_post)
                                        .addGap(8, 8, 8)
                                        .addComponent(TextField_post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_ID)
                                .addGap(8, 8, 8)
                                .addComponent(TextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Label_phone)
                                .addGap(8, 8, 8)
                                .addComponent(TextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_bd)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Label_gender)
                        .addGap(8, 8, 8)
                        .addComponent(TextField_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_age)
                    .addComponent(Label_password))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_posion)
                .addGap(8, 8, 8)
                .addComponent(TextField_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Label_create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_create.setText("Create an account");

        Button_ok.setText("OK");
        Button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_okActionPerformed(evt);
            }
        });

        Button_cancel.setText("Cancel");
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_create)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_create)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_fnameActionPerformed
        Fname = TextField_fname.getText();
        TextField_sir.requestFocus();
    }//GEN-LAST:event_TextField_fnameActionPerformed

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Button_cancelActionPerformed

    private void TextField_sirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_sirActionPerformed
        Lname = TextField_sir.getText();
        TextField_add.requestFocus();
    }//GEN-LAST:event_TextField_sirActionPerformed

    private void TextField_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_addActionPerformed
        Address1 = TextField_add.getText();
        TextField_subdist.requestFocus();
    }//GEN-LAST:event_TextField_addActionPerformed

    private void TextField_subdistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_subdistActionPerformed
        Address2 = TextField_subdist.getText();
        TextField_dist.requestFocus();
    }//GEN-LAST:event_TextField_subdistActionPerformed

    private void TextField_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_provActionPerformed
        Address4 = TextField_prov.getText();
        TextField_post.requestFocus();
    }//GEN-LAST:event_TextField_provActionPerformed

    private void TextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_IDActionPerformed
        In = TextField_ID.getText();
        TextField_phone.requestFocus();
    }//GEN-LAST:event_TextField_IDActionPerformed

    private void TextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_phoneActionPerformed
        pno = TextField_phone.getText();
        TextField_bd.requestFocus();
    }//GEN-LAST:event_TextField_phoneActionPerformed

    private void TextField_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_bdActionPerformed
        birth = TextField_bd.getText();
        TextField_gender.requestFocus();
    }//GEN-LAST:event_TextField_bdActionPerformed

    private void TextField_distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_distActionPerformed
        Address3 = TextField_dist.getText();
        TextField_prov.requestFocus();
    }//GEN-LAST:event_TextField_distActionPerformed

    private void TextField_postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_postActionPerformed
        Address5 = TextField_post.getText();
        TextField_ID.requestFocus();
    }//GEN-LAST:event_TextField_postActionPerformed

    private void Button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_okActionPerformed
        Address_total = Address1 + ", " + Address2 + ", " + Address3 + ", " + Address4 + ", " + Address5;
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Employee");
            BasicDBObject document = new BasicDBObject();
            BasicDBObject searchQuery = new BasicDBObject();

            searchQuery.put("MS_Employee_In", In);
            DBCursor cursor = table.find(searchQuery);
            while (cursor.hasNext()) {
                System.out.println(cursor.next());
                FoundIn = true;
            }

            if (FoundIn == false) {
                getUsername();
                document.put("MS_Employee_Id", username);
                document.put("MS_Employee_In", In);
                document.put("MS_Employee_Fname", Fname);
                document.put("MS_Employee_Lname", Lname);
                document.put("MS_Employee_Gender", gender);
                document.put("MS_Employee_Age", age);
                document.put("MS_Employee_Phone", pno);
                document.put("MS_Employee_Address", Address_total);
                document.put("MS_Employee_Pass", password);
                document.put("MS_Employee_Type", position);
                table.insert(document);
                System.out.println("ok, your username is "+username+"and password is"+ password);
                JOptionPane.showMessageDialog(this, "OK, Your username is "+username+" and password is "+password);
                this.setVisible(false);
                System.exit(0);

            } else {
                System.out.println("please try again");
                JOptionPane.showMessageDialog(this, "Please select another identified number.");
                TextField_ID.setText("");
                In = "";
                FoundIn = false;
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_Button_okActionPerformed

    private void TextField_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_genderActionPerformed
        gender = TextField_gender.getText();
        TextField_age.requestFocus();
    }//GEN-LAST:event_TextField_genderActionPerformed

    private void TextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ageActionPerformed
        age = TextField_age.getText();
        TextField_password.requestFocus();
    }//GEN-LAST:event_TextField_ageActionPerformed

    private void TextField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_passwordActionPerformed
        password = TextField_password.getText();
        TextField_position.requestFocus();
    }//GEN-LAST:event_TextField_passwordActionPerformed

    private void TextField_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_positionActionPerformed
        position = TextField_position.getText();
        Button_ok.requestFocus();
    }//GEN-LAST:event_TextField_positionActionPerformed

    private static void getUsername() {
        try {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("inthanin");
            DBCollection table = db.getCollection("MS_Employee");
            DBCursor cursor = table.find();
            count = cursor.count();
        } catch (Exception e) {
        }
        if (count > 99 || count == 99) {
            username = "E" + (count + 1);
        } else if (count > 9 || count == 9) {
            username = "E0" + (count + 1);
        } else {
            username = "E00" + (count + 1);
        }
        System.out.println(username);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_cancel;
    private javax.swing.JButton Button_ok;
    private javax.swing.JLabel Label_Add;
    private javax.swing.JLabel Label_ID;
    private javax.swing.JLabel Label_Subdist;
    private javax.swing.JLabel Label_age;
    private javax.swing.JLabel Label_bd;
    private javax.swing.JLabel Label_create;
    private javax.swing.JLabel Label_dist;
    private javax.swing.JLabel Label_fname;
    private javax.swing.JLabel Label_gender;
    private javax.swing.JLabel Label_password;
    private javax.swing.JLabel Label_phone;
    private javax.swing.JLabel Label_posion;
    private javax.swing.JLabel Label_post;
    private javax.swing.JLabel Label_prov;
    private javax.swing.JLabel Label_sir;
    private javax.swing.JTextField TextField_ID;
    private javax.swing.JTextField TextField_add;
    private javax.swing.JTextField TextField_age;
    private javax.swing.JTextField TextField_bd;
    private javax.swing.JTextField TextField_dist;
    private javax.swing.JTextField TextField_fname;
    private javax.swing.JTextField TextField_gender;
    private javax.swing.JTextField TextField_password;
    private javax.swing.JTextField TextField_phone;
    private javax.swing.JTextField TextField_position;
    private javax.swing.JTextField TextField_post;
    private javax.swing.JTextField TextField_prov;
    private javax.swing.JTextField TextField_sir;
    private javax.swing.JTextField TextField_subdist;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
